name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: './resume builder/package-lock.json'
          
      - name: Install dependencies
        run: |
          cd "resume builder"
          npm ci
          
      - name: Build
        run: |
          cd "resume builder"
          npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: /new-resume
          NODE_ENV: production
          
      - name: Create .nojekyll files
        run: |
          touch ".nojekyll"
          touch "resume builder/out/.nojekyll"
          
      - name: Copy index.html to 404.html for SPA routing
        run: |
          cp "resume builder/out/index.html" "resume builder/out/404.html"
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './resume builder/out'
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3 